# ---------------------------------------------------------------------------------------------
# Makefile Automation
# 
# Streamlines running the main program and cleaning up the directory by removing old output 
# files.
#
# Usage:
#   $ make <target>
# ---------------------------------------------------------------------------------------------
# Run the main program.
all:
	@python3 eye_blur.py

# Remove all the output files.
clean:
	@rm *_output.jpg