# -----------------------------------------------------------------------------
# Makefile
#
# Bash automation.
#
# Usage:
#   $ make <target>
# -----------------------------------------------------------------------------
# Run all targets.
all: check
	
# Run python check file.
check:
	@python3 check.py