# --------------------------------------------------------------------------------------
# Chatty Chatbot - Information Bits
#
# List of random bits of information to start the conversation.
#
# Usage:
#   from info_bits import INFO_BITS
# --------------------------------------------------------------------------------------
INFO_BITS = [
    "Bananas are berries, but strawberries are not.",
    "Honey never spoils and can last thousands of years.",
    "A group of flamingos is called a 'flamboyance'.",
    "The Eiffel Tower can be 15 cm taller during hot days.",
    "Octopuses have three hearts.",
    "Some turtles can breathe through their butts.",
    "There are more stars in the universe than grains of sand on Earth.",
    "Wombat poop is cube-shaped.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "A day on Venus is longer than a year on Venus.",
    "The shortest war in history lasted just 38 minutes.",
    "Sloths can hold their breath longer than dolphins can.",
    "The unicorn is the national animal of Scotland.",
    "Mosquitoes are attracted to people who just ate bananas.",
    "A jiffy is an actual unit of time: 1/100th of a second.",
    "The dot over a lowercase 'i' or 'j' is called a tittle.",
    "Butterflies taste with their feet.",
    "There are more fake flamingos in the world than real ones.",
    "Hot water freezes faster than cold water under certain conditions.",
    "Some cats are allergic to humans.",
    "The heart of a shrimp is located in its head.",
    "A group of porcupines is called a prickle.",
    "The longest English word without a true vowel is 'rhythms'.",
    "The inventor of the microwave appliance only received $2 for his discovery.",
    "A cloud can weigh more than a million pounds.",
    "Venus is the only planet that spins clockwise.",
    "The fingerprints of a koala are so indistinguishable from humans that they have on occasion confused crime scene investigators.",
    "A snail can sleep for three years.",
    "The tongue of a blue whale weighs as much as an elephant.",
    "Cows have best friends and can become stressed if separated from them.",
    "The wood frog can hold its pee for up to eight months.",
    "The inventor of the Rubik's Cube couldn't solve it for over a month.",
    "The first computer mouse was made of wood.",
    "A group of crows is called a murder.",
    "The world's largest grand piano was built by a 15-year-old in New Zealand.",
    "The electric chair was invented by a dentist.",
    "The inventor of Vaseline ate a spoonful of it every morning.",
    "The Twitter bird actually has a name – Larry.",
    "A group of ferrets is called a business.",
    "The hashtag symbol is technically called an octothorpe.",
    "The first oranges weren’t orange, but green.",
    "The inventor of Pringles is buried in a Pringles can.",
    "A group of owls is called a parliament.",
    "The inventor of the Super Soaker was a NASA engineer.",
    "The longest wedding veil was the same length as 63.5 football fields.",
    "The inventor of the Post-it Note accidentally created the adhesive while trying to develop a super-strong glue.",
    "The inventor of the matchstick was a British pharmacist named John Walker.",
    "The inventor of the trampoline was a gymnast named George Nissen.",
    "The inventor of the popsicle was an 11-year-old boy.",
    "The inventor of the ballpoint pen was a Hungarian journalist named László Bíró."
]