# --------------------------------------------------------------------------------------------
# Makefile Automation
#
# Streamlines the commands to execute the program and clean up the directory.
#
# Usage:
#   make <target>
# --------------------------------------------------------------------------------------------
# Runs all targets.
all: python clean

# Launches the python program.
python:
	@python3 driver.py

# Cleans up the directory.
clean:
	@rm -rf __pycache__